from typing import AsyncIterable, Optional
from datetime import timedelta
from tokio_raft import types, options, membership
from tokio_raft import AsyncReader

class Raft:
  def reloadable_options(self) -> options.ReloadableOptions: ...
  
  def options(self) -> options.Options: ...
  
  def local_id(self) -> types.NodeId: ...
  
  def local_addr(self) -> types.NodeAddress: ...
  
  def role(self) -> types.Role: ...
  
  def current_term(self) -> int: ...
  
  def latest_membership(self) -> membership.LastMembership: ...
  
  def last_contact(self) -> Optional[timedelta]: ...
  
  def last_index(self) -> int: ...
  
  def commit_index(self) -> int: ...
  
  def applied_index(self) -> int: ...
  
  def leader(self) -> types.Node: ...

  async def leadership_watcher(self) -> AsyncIterable[bool] : ...
  
  async def leadership_change_watcher(self) -> AsyncIterable[bool] : ...
  
  async def apply(self, data: bytes) -> types.ApplyFuture : ...

  async def apply_timeout(self, timeout: timedelta) -> types.ApplyFuture : ...

  async def barrier(self) -> types.BarrierFuture: ...
  
  async def barrier_timeout(self, timeout: timedelta) -> types.BarrierFuture: ...

  async def snapshot(self) -> types.SnapshotFuture: ...

  async def snapshot_timeout(self, timeout: timedelta) -> types.SnapshotFuture: ...

  async def verify_leader(self) -> types.VerifyFuture: ...
  
  async def add_voter(self, id: types.NodeId, addr: types.NodeAddress, prev_index: int) -> types.MembershipChangeFuture:...
  
  async def add_voter_timeout(self, id: types.NodeId, addr: types.NodeAddress, prev_index: int, timeout: timedelta) -> types.MembershipChangeFuture:...
  
  async def add_nonvoter(self, id: types.NodeId, addr: types.NodeAddress, prev_index: int) -> types.MembershipChangeFuture:...

  async def add_nonvoter_timeout(self, id: types.NodeId, addr: types.NodeAddress, prev_index: int, timeout: timedelta) -> types.MembershipChangeFuture:...

  async def demote_voter(self, id: types.NodeId, prev_index: int) -> types.MembershipChangeFuture:...

  async def demote_voter_timeout(self, id: types.NodeId, prev_index: int, timeout: timedelta) -> types.MembershipChangeFuture:...
  
  async def remove(self, id: types.NodeId, prev_index: int) -> types.MembershipChangeFuture:...

  async def remove_timeout(self, id: types.NodeId, prev_index: int, timeout: timedelta) -> types.MembershipChangeFuture:...
  
  async def reload_options(self, options: options.ReloadableOptions) -> None :...
  
  async def restore(self, reader: AsyncReader) -> None :...
  
  async def restore_timeout(self, reader: AsyncReader, timeout: timedelta) -> None :...

  async def leadership_transfer(self) -> types.LeadershipTransferFuture:...
  
  async def leadership_transfer_to_node(self, id: types.NodeId, addr: types.NodeAddress) -> types.LeadershipTransferFuture:...

  async def stats(self) -> types.RaftStats:...

  async def shutdown(self) -> bool :...
