[package]
name = "ruraft"
version = { workspace = true } 
edition = { workspace = true }
license = { workspace = true }
description = "A placeholder"

[dependencies]
bytes = { workspace = true }
ruraft-core = { path = "../core" }
