[package]
name = "ruraft"
version = { workspace = true } 
edition = { workspace = true }
license = { workspace = true }
description = "A placeholder"

[features]
default = []

tokio = ["agnostic/tokio"]
async-std = ["agnostic/async-std"]
smol = ["agnostic/smol"]

# enable DNS node address resolver
dns = ["trust-dns-resolver", "trust-dns-proto", "idna", "agnostic/dns"]

# enable DNS node address resolver with WASI support
dns-wasi = ["resolv-conf", "trust-dns-resolver", "trust-dns-proto", "idna", "agnostic/dns"]


[target.'cfg(not(target_family = "wasm"))'.dependencies]
trust-dns-resolver = { version = "0.23", default-features = false, optional = true, features = ["system-config"] }

[target.'cfg(target_family = "wasm")'.dependencies]
trust-dns-resolver = { version = "0.23", default-features = false, optional = true }


[dependencies]
agnostic = { workspace = true }
async-channel = { workspace = true }
async-lock = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
crossbeam-skiplist = "0.1"
futures = { workspace = true }
ruraft-core = { path = "../core" }
smol_str = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

resolv-conf = { version = "0.7", default-features = false, optional = true }
trust-dns-proto = { version = "0.23", default-features = false, optional = true }
idna = { version = "0.4", optional = true }